### ISSUE TITLE
How to add rotation function correctly?

### ISSUE THREAD

**Issue by myuanz** [andyborrell/imgui_tex_inspect#2]
I'm trying to add a rotation function to inspect. I tracked the source code until I saw a projection variable (ortho_projection) in the shader, I think this should be what I'm looking for.

https://github.com/andyborrell/imgui_tex_inspect/blob/1c9c0faa0cc0c62b565523a05ea4622bc0f0a307/backends/tex_inspect_opengl.cpp#L262-L268

https://github.com/andyborrell/imgui_tex_inspect/blob/1c9c0faa0cc0c62b565523a05ea4622bc0f0a307/backends/tex_inspect_opengl.cpp#L348-L360

But after I modified this matrix, I found that the image position will change when I drag the image window, and the image will also deviate when I drag the image content and when I scroll. I added a 30° rotation and the result is as shown in the figure. 

https://user-images.githubusercontent.com/25359546/136394805-7e821700-dd58-4723-bc23-e1680234c06b.mp4

Rotation matrix is: 

```math
 sin(30°),  cos(60°),  0.00,  0.00, 
-cos(60°),  sin(30°),  0.00,  0.00, 
 0.00,      0.00,      1.00,  0.00, 
 0.00,      0.00,      0.00,  1.00, 
```

**Comment by andyborrell** [comment]
Changing the projection matrix isn't going to do what you want.  If you do rotate the projection matrix it will mean that the rectangle which is drawn for the image by ImGui will be a rotated rectangle.  This might sound good, but think about when zoomed in, when you're zoomed in on a rotated image what you see should still be a screen aligned rectangular subwindow in that image.  So we want it to stay rectangular.  

You also might think of rotating the UV values which are used in the shader to sample the source texture.  However this will also introduce problems since the tooltip and annotations would still show information as if they were over the unrotated image, panning wouldn't go the way you expect, and also you might have trouble scrolling to the corners which would now be outside the bounds of the unrotated image.

So unfortunately it would be significant work to add support for rotating images.

What I recommend you do is just create a frame buffer and render your source texture on to a new texture at the rotated angle.  Then you can use ImGuiTexInspect to view that new texture.  Then all the features would work correctly.

**Comment by myuanz** [comment]
Thank you, it seems the only way, I will try.

**Comment by myuanz** [comment]
We have some other features such as "stylize image", "adjust color range", "merge pixel scaling". We plan to use it as a part of a gene viewing tool, would you accept if I add a fragment shader chain or something to achieve these functions? Are these features suitable to add to inspect?

**Comment by andyborrell** [comment]
I don't know what you'd want those shaders to do, but "adjust color range" sounds like something that could already be done from the default inspector shader just by setting the color matrix.

Adding different more application-specific shaders probably isn't something I'd want to add.  The problem with adding a new shader is that it would need to be added for every supported platform, i.e. different versions of OpenGL and DirectX, and any other later supported platforms.

There might be specific functionality I'd be willing to merge into the existing shader.  Perhaps if you explain what those 3 features would do then I could say whether it's something that might make sense to merge in.

**Comment by myuanz** [comment]
Thanks for your reply, I do feel now that there are some things that are not suitable to add and might be more suitable for another as a new project. I can talk about these features casually.

We often use a method called "bin scaling" to look at genes with very low expression in the wide range, where bin N means summing up the gene expression in the NxN region and presenting it as a pixel, which I call "merge pixel scaling" above.

Since gene expressions do not always fall in the regular color values (UInt8 or UInt16), we often need to normalize by the appropriate gamma value, and sometimes we need to ignore data with expressions greater than certain values. I call this "adjust color range" in the above.

At other times, we also need to generate a pseudo-color image of the expression, the process involves several separate steps and therefore may require a chain of shaders, which I call "stylize image" above.
